apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
- ../../../components/argocd/config-pipeline-operator/base
- ../../../config-cluster-namespaces/base
#- ../../../components/argocd/config-pipeline-tasks/base
