apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
- ../../../components/argocd/apps/config-pipeline-operator/base
- ../../../components/argocd/apps/config-cluster-namespaces/base
- ../../../components/argocd/apps/config-cluster-pipelines/base
