apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

resources:
- github-sealed-secret.yaml

patchesJson6902:
  - path: patch-source-dirs.yaml
    target:
      group: triggers.tekton.dev
      version: v1alpha1
      kind: TriggerTemplate
      name: cluster-admin-pipeline-template


