apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-pipelines-app
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: cluster-pipelines
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/apps/cluster-pipelines/overlays
    repoURL: https://github.com/ldesrosi/cluster-config.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true