apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-pipeline-tasks
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: cluster-gitops-repo-pipelines
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: tasks
    repoURL: https://github.com/ldesrosi/ibm-garage-tekton-tasks.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false