apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '1'
  labels:
    gitops.ownedBy: cluster-config
  name: cluster-namespaces
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/apps/cluster-namespaces/base
    repoURL: https://github.com/ldesrosi/cluster-config.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true