apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: validate-manifests
spec:
  params:
    - name: source-dirs
      default: 
      - /source
      type: array
  resources:
    inputs:
      - name: source
        type: git
  results:
    - name: status
      description: Status can be one of ['Passed','Failed']
  steps:
    - name: process-source-repo
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env bash

        ls -al /workspace/source | tee $(results.status.path)

