apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cluster-admin-pipeline-template
spec:
  params:
    - name: git-revision
      description: The git revision (SHA)
      default: master
    - name: git-repository-url
      description: The git repository url ("https://github.com/foo/bar.git")
    - name: git-status-url
      description: The status api url 
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: validate-manifests-run-
      spec:
        pipelineRef:
          name: validate-manifests-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-repository-url)
          - name: git-status-url
            value: $(tt.params.git-status-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: source-list
            value: 
              - /
        resources:
          - name: source
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(tt.params.git-revision)
                - name: url
                  value: $(tt.params.git-repository-url)
