apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-pr
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-interceptor-secret
              secretKey: secretToken
            eventTypes: ["pull_request"]
        - cel:
            filter: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: cluster-admin-pr-binding
      template:
        ref: cluster-admin-pipeline-template
