apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: cluster-admin-pr-binding
spec:
  params:
    - name: git-repository-url
      value: $(body.repository.clone_url)
    - name: git-status-url
      value: $(body.repository.statuses_url)
    - name: git-revision
      value: $(body.pull_request.head.sha)