apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: validate-manifests-pipeline
spec:
  params:
    - name: source-dirs
      type: array
      description: List of folders within the source PR that requires validation.
  resources:
    - name: source
      type: git
  tasks:
    - name: validate-manifests
      taskRef:
        kind: Task
        name: validate-manifests
      resources:
        inputs:
          - name: source
            resource: source
      params:
        - name: source-dirs
          value: $(params.source-dirs[*])

